#! /usr/bin/env bash
set -e

# dependencies
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y curl wget git apt-transport-https \
                   libpq-dev libsqlite3-dev libsasl2-dev \
                   postgresql-client postgresql postgresql-contrib \
                   sudo vim zlib1g-dev supervisor psmisc \
                   rsync jq netcat-openbsd \
                   libunwind8 sqlite3 libc++abi1-12 libc++1-12 # stellar-core runtime deps
apt-get clean
rm -rf /var/lib/apt/lists/*

echo "\nDone installing dependencies...\n"
