#! /usr/bin/env bash
set -e

# dependencies (Ubuntu 24.04 noble)
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y curl wget git ca-certificates apt-transport-https \
                   libpq-dev libsqlite3-dev libsasl2-dev \
                   postgresql-client-16 postgresql-16 postgresql-contrib-16 \
                   sudo vim zlib1g-dev supervisor psmisc \
                   rsync jq netcat-openbsd \
                   libunwind8 sqlite3 libc++abi1-20 libc++1-20  # stellar-core runtime deps

apt-get clean
rm -rf /var/lib/apt/lists/*

echo "\nDone installing dependencies...\n"
