#! /usr/bin/env bash
set -e

# dependencies
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y curl wget git apt-transport-https \
                   libpq-dev libsqlite3-dev libsasl2-dev \
                   postgresql-client postgresql postgresql-contrib \
                   sudo vim zlib1g-dev supervisor psmisc \
                   jq netcat # Parsing stellar-core JSON and checking core HTTP server
apt-get clean

echo "\nDone installing dependencies...\n"
