FROM golang:1.23 AS builder

ARG REF
WORKDIR /go/src/github.com/stellar/go
RUN git clone https://github.com/stellar/go /go/src/github.com/stellar/go
RUN git fetch origin ${REF}
RUN git checkout ${REF}
RUN COMMIT=$(git rev-parse HEAD) && \
    VERSION=${REF#horizon-v} && \
    CGO_ENABLED=0 go install \
    -ldflags="-X github.com/stellar/go/support/app.version=${VERSION}-${COMMIT}" \
    github.com/stellar/go/services/horizon
