FROM golang:1.24 AS builder

ARG REF
WORKDIR /src
RUN git clone https://github.com/stellar/stellar-horizon /src
RUN git fetch origin ${REF}
RUN git checkout ${REF}
ENV CGO_ENABLED=0
RUN go build -o /go/bin/horizon github.com/stellar/stellar-horizon
