services:
  mainnet:
    image: pinetwork/pi-node-docker:community-v1.0-p19.9
    command: --mainnet
    volumes:
      - stellar_data:/opt/stellar
    ports:
      - "8000:8000"
      - "31402:31402"
    environment:
      POSTGRES_PASSWORD: postgres
    profiles: [mainnet]

  testnet:
    image: pinetwork/pi-node-docker:community-v1.0-p19.9
    command: --testnet
    volumes:
      - stellar_data:/opt/stellar
    ports:
      - "8000:8000"
      - "31402:31402"
    environment:
      POSTGRES_PASSWORD: postgres
    profiles: [testnet]

  testnet2:
    image: pinetwork/pi-node-docker:community-v1.0-p19.9
    container_name: pi-testnet2
    command: --testnet2
    volumes:
      - testnet2_stellar_data:/opt/stellar
    ports:
      - "8000:8000"
      - "31402:31402"
    environment:
      POSTGRES_PASSWORD: postgres
    profiles: [testnet2]

volumes:
  stellar_data:
  testnet2_stellar_data:

